config/routes.rb
Rails.application.routes.draw do

  get  "/edit-profile", to: "users#edit"
  patch  "/edit-profile", to: "users#update"
  delete "/edit-profile", to: "users#destroy"

  get 'bookings/show'

  get 'bookings/new'

  get 'bookings/create'

  get 'bookings/edit'

  get 'bookings/update'

  get 'bookings/destroy'

  devise_for :users
  resources :gardens do
    resources :reviews, only: [:new, :create]
    resources :bookings, only:[:new, :create, :show, :edit]
  end

  get "/dashboard", to: "users#dashboard"

  # namespace :admin do
  #   resources :gardens, only: [:index]
  # end

  get 'about' => "pages#about"

  get 'pages/home'

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :garden
end

app/models/garden.rb
class Garden < ApplicationRecord
  # include PgSearch
  # pg_search_scope :search_params, against: [ :city ]

  validates :name, uniqueness: true, presence: true
  validates :price, presence: true
  validates :city, presence: true
  validates :capacity, presence: true

  has_many  :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :garden
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gardens, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def new
    @booking = Booking.new
    @booking.date_check_in = params[:date_check_in]

    @garden = Garden.find(params[:garden_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.garden = Garden.find(params[:garden_id])
    @booking.save
    if @booking.save
      redirect_to dashboard_path, notice: 'Votre réservation a bien été enregistrée.'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  private

  def booking_params
    params.require(:booking).permit(:date_check_in, :price)
  end

end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    if params[:city] != ""
      @gardens = Garden.where(city: params[:city])
    else
      @gardens = Garden.all
    end
  end

  def show
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(params[:garden])
    if @garden.save
      redirect_to gardens_path(@garden)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @garden.update(garden_params)
    redirect_to garden_path(@garden)
  end

  def destroy
    @garden.destroy
    redirect_to gardens_path
  end


  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name, :description, :city)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_garden

  def new
    @review = @garden.reviews.build
  end

  def create
    @review = Review.new(review_params)
    @review.garden = @garden
    @review.save
    redirect_to garden_path(@garden)
  end

  private
  def set_garden
    @garden = Garden.find(params[:garden_id])
  end
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Récapitulatif de la réservation souhaitée</p>

<h4>Dates de réservation</h4>
<p>Date de réservation</p>
<p> <%= @booking.date_check_in %> </p>

<h4>Le jardin</h4>
<p>Nom :</p>
<p> <%= @garden.name %> </p>
<p>Ville :</p>
<p> <%= @garden.city %> </p>
<p>Capacité :</p>
<p> <%= @garden.capacity %> </p>

<div id="btn">
  <%= simple_form_for [@garden, @booking] do |f| %>
  <%= f.input :date_check_in, as: :hidden %>
  <%= f.submit "Confirmer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/gardens/create.html.erb
<h1>Gardens#create</h1>
<p>Find me in app/views/gardens/create.html.erb</p>

app/views/gardens/destroy.html.erb
<h1>Gardens#destroy</h1>
<p>Find me in app/views/gardens/destroy.html.erb</p>

app/views/gardens/edit.html.erb
<h1>Gardens#edit</h1>
<p>Find me in app/views/gardens/edit.html.erb</p>


<%= form_for(@garden) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :city %>
  <%= f.number_field :capacity %>

  <%= f.submit %>
<% end %>

app/views/gardens/index.html.erb
<div class="index-container">

  <div class="cards-container">
    <h1>Les jardins disponibles</h1>
    <% @gardens.each do |garden| %>
      <div class="col-xs-12 col-sm-4">
        <%= link_to garden_path(garden, request.query_parameters) do %>
          <div class="card-index">
            <div class="card-title">
              <h6><%= garden.name %></h6>
              <span>Ville : <%= garden.city %></span>
            </div>
            <div class="card-capacity">
              <span>Ville : <%= garden.capacity %></span>
            </div>
            <div class="card-price">
              <span>Prix : <%= garden.price %> €/j</span>
            </div>
          </div>
          <%= link_to "Détails", garden_path(garden) %>
          <%= link_to "Editer", edit_garden_path(garden) %>
          <%= link_to "Supprimer", garden_path(garden), method: :delete %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="map-container">

  </div>
</div>

app/views/gardens/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
      <h1>Gardens#new</h1>
      <p>Créez un nouveau jardin</p>

      <%= simple_form_for @garden do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :city %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :description %>

        <%= f.submit "Enregistrer", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/show.html.erb
<h2><%= @garden.name %></h2>
<p><%= @garden.description %></p>
<span>Ville : <%= @garden.city %></span>
<span>Prix : <%= @garden.price %> €/j</span>

<ul>
  <% @garden.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>

<%= link_to "Booker", new_garden_booking_path(@garden) %>

<%= link_to "Retour à la liste", gardens_path %>
<%= link_to "Ajouter une review", new_garden_review_path(@garden) %>

app/views/gardens/update.html.erb
<h1>Gardens#update</h1>
<p>Find me in app/views/gardens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plateforme</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Nous louons des jardins entre particuliers</h1>
<p>un projet fondé en 2017</p>

app/views/pages/home.html.erb
<div class="home-wrapper">
  <div class="home-container" style="background-image: url('<%= image_url "garden-home.jpg" %>'); background-size: cover; height: 100vh">
    <div class="home-texte text-center">
      <h1>Gardeny</h1>
      <p>Find your garden to party</p>

      <form action="/gardens" method="get" class="form-inline text-center padded">
        <div class="form-group">
          <label class="sr-only" for="inlineFormInput">City</label>
          <input class="form-control" type="text" id="inlineFormInput" placeholder="Paris" name="city">
        </div>

        <div class="form-group">
          <label for="checkin" class="sr-only">Checkin</label>
          <input class="form-control" type="date" id="checkin" name="date_check_in"value="<%= Date.today %>">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      </form>

    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Ajoutez une review pour le jardin <%= @garden.name %></h1>

<%= form_for [@garden, @review] do |f| %>



  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="../../../assets/images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href=" <%= new_garden_path %>" class="navbar-wagon-item navbar-wagon-link">Enregistrer un jardin</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to dashboard_path %></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
dashboard.html.erb

app/views/users/edit.html.erb
edit.html.erb

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>